sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
  - cache
  - dependencies
language: elixir
matrix:
  include:
    - elixir: 1.4.0
      env: IDEA_TARBALL_ROOT_BASENAME="idea-IC-163.9166.29" IDEA_VERSION="2016.3.1"
      jdk: oraclejdk8
      otp_release: 19.2
    - elixir: 1.3.4
      env: IDEA_TARBALL_ROOT_BASENAME="idea-IC-163.9166.29" IDEA_VERSION="2016.3.1"
      jdk: oraclejdk8
      otp_release: 19.2
    - elixir: 1.2.6
      env: IDEA_TARBALL_ROOT_BASENAME="idea-IC-163.9166.29" IDEA_VERSION="2016.3.1"
      jdk: oraclejdk8
      otp_release: 18.3
    - elixir: 1.1.1
      env: IDEA_TARBALL_ROOT_BASENAME="idea-IC-163.9166.29" IDEA_VERSION="2016.3.1"
      jdk: oraclejdk8
      otp_release: 18.3

    - elixir: 1.4.0
      env: IDEA_TARBALL_ROOT_BASENAME="idea-IC-143.2370.31" IDEA_VERSION="15.0.6"
      jdk: oraclejdk8
      otp_release: 19.2
    - elixir: 1.3.4
      env: IDEA_TARBALL_ROOT_BASENAME="idea-IC-143.2370.31" IDEA_VERSION="15.0.6"
      jdk: oraclejdk8
      otp_release: 19.2
    - elixir: 1.2.6
      env: IDEA_TARBALL_ROOT_BASENAME="idea-IC-143.2370.31" IDEA_VERSION="15.0.6"
      jdk: oraclejdk8
      otp_release: 18.3
    - elixir: 1.1.1
      env: IDEA_TARBALL_ROOT_BASENAME="idea-IC-143.2370.31" IDEA_VERSION="15.0.6"
      jdk: oraclejdk8
      otp_release: 18.3

    - elixir: 1.4.0
      env: IDEA_TARBALL_ROOT_BASENAME="idea-IC-141.3058.30" IDEA_VERSION="14.1.7"
      jdk: openjdk6
      otp_release: 19.2
    - elixir: 1.3.4
      env: IDEA_TARBALL_ROOT_BASENAME="idea-IC-141.3058.30" IDEA_VERSION="14.1.7"
      jdk: openjdk6
      otp_release: 19.2
    - elixir: 1.2.6
      env: IDEA_TARBALL_ROOT_BASENAME="idea-IC-141.3058.30" IDEA_VERSION="14.1.7"
      jdk: openjdk6
      otp_release: 18.3
    - elixir: 1.1.1
      env: IDEA_TARBALL_ROOT_BASENAME="idea-IC-141.3058.30" IDEA_VERSION="14.1.7"
      jdk: openjdk6
      otp_release: 18.3
before_install:
- "export ELIXIR_VERSION=${TRAVIS_ELIXIR_VERSION}"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- "wget --no-check-certificate --no-cookies --header \"Cookie: oraclelicense=accept-securebackup-cookie\" http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.tar.gz"
- tar xvfz jdk-8u112-linux-x64.tar.gz
- export JAVA_HOME=${PWD}/jdk1.8.0_112
- export PATH=${JAVA_HOME}/bin:${PATH}
- wget http://www-us.apache.org/dist//ant/binaries/apache-ant-1.10.1-bin.tar.gz
- tar xvfz apache-ant-1.10.1-bin.tar.gz
- export PATH=${PWD}/apache-ant-1.10.1/bin:${PATH}
- java -version
- ant -version
install:
  - ant -logger org.apache.tools.ant.listener.AnsiColorLogger -f intellij-elixir.xml get.idea get.intellij-erlang release.intellij_elixir
script:  ant -logger org.apache.tools.ant.listener.AnsiColorLogger -f intellij-elixir.xml test.modules
sudo: false
